export enum SECTION_TCP {
  ADMIN_ADD_SECTION = 'ADMIN_ADD_SECTION',
  ADMIN_GET_ALL_SECTION = 'ADMIN_GET_ALL_SECTION',
  ADMIN_DELETE_SECTION_BY_ID = 'ADMIN_DELETE_SECTION_BY_ID',
  ADMIN_FIND_ALL_TEACHER_ACCORDING_TO_SECTION = 'ADMIN_FIND_ALL_TEACHER_ACCORDING_TO_SECTION',
  ADMIN_FIND_ALL_STUDENT_ACCORDING_TO_SECTION = 'ADMIN_FIND_ALL_STUDENT_ACCORDING_TO_SECTION',
}
