export enum ADMIN_TCP {
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  ADMIN_REGISTER_TEACHER = 'ADMIN_REGISTER_TEACHER',
  ADMIN_REGISTER_STUDENT = 'ADMIN_REGISTER_STUDENT',
  ADMIN_GET_ALL_TEACHER = 'ADMIN_GET_ALL_TEACHER',
  ADMIN_ADD_FACULTY = 'ADMIN_ADD_FACULTY',
  ADMIN_GET_ALL_FACULTY = 'ADMIN_GET_ALL_FACULTY',
  ADMIN_EDIT_FACULTY = 'ADMIN_EDIT_FACULTY',
  ADMIN_DELETE_FACULTY_BY_ID = 'ADMIN_DELETE_FACULTY_BY_ID',
  ADMIN_UPDATE_TEACHER_BY_ID = 'ADMIN_UPDATE_TEACHER_BY_ID',
  ADMIN_DELETE_TEACHER_BY_ID = 'ADMIN_DELETE_TEACHER_BY_ID',
}
