export enum ADMIN_TCP {
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  ADMIN_REGISTER_TEACHER = 'ADMIN_REGISTER_TEACHER',
  ADMIN_REGISTER_STUDENT = 'ADMIN_REGISTER_STUDENT',
  ADMIN_ADD_COURSE = 'ADMIN_ADD_COURSE',
  ADMIN_GET_ALL_TEACHER = 'ADMIN_GET_ALL_TEACHER',
}
