export enum TEACHER_TCP {
  LOGIN = 'LOGIN',
  GET_PROFILE = 'GET_PROFILE',
  GET_SECTIONS_ACCORDING_TO_TEACHER = 'GET_SECTIONS_ACCORDING_TO_TEACHER',
  TEACHER_ADD_STUDENT_ATTENDANCE = 'TEACHER_ADD_STUDENT_ATTENDANCE',
  TEACHER_GET_STUDENT_ATTENDANCE = 'TEACHER_GET_STUDENT_ATTENDANCE',
  TEACHER_ADD_ABSENT_STUDENT_ATTENDANCE = 'TEACHER_ADD_ABSENT_STUDENT_ATTENDANCE',
}
